AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
